import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

/**
 * Exports an HTML element to PDF without flickering/blinking.
 * Uses html2canvas's onclone feature to modify a virtual copy of the DOM.
 */
export async function exportNoteToPdf({ element, fileName }) {
  if (!element) return;

  try {
    // 1. Capture Canvas using onclone to avoid flickering
    const canvas = await html2canvas(element, {
      scale: 2, // High resolution
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
      windowWidth: 800, // Fixed width for consistent layout
      onclone: (clonedDoc) => {
        // Find the specific content in the virtual cloned document
        const clonedElement = clonedDoc.getElementById('pdf-content');

        if (clonedElement) {
          // --- Force Light Mode in Clone ONLY ---
          clonedDoc.documentElement.classList.remove('dark');
          clonedDoc.body.classList.remove('dark');
          clonedDoc.body.style.backgroundColor = '#ffffff';

          // --- Apply PDF Styling to Clone ONLY ---
          clonedElement.style.width = '800px';
          clonedElement.style.padding = '40px';
          clonedElement.style.margin = '0 auto';
          clonedElement.style.backgroundColor = '#ffffff';
          clonedElement.classList.add('pdf-mode');

          // Ensure all text is visible (force white background/black text)
          // index.css already has .pdf-mode rules, but we double down here
          clonedElement.style.color = '#000000';
        }
      }
    });

    // 2. Initialize PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = 210;
    const pdfHeight = 297;
    const canvasWidth = canvas.width;
    const canvasHeight = canvas.height;

    // Calculate aspect ratio
    const imgWidth = pdfWidth;
    const imgHeight = (canvasHeight * pdfWidth) / canvasWidth;

    // Watermark Helper
    const addWatermark = (p) => {
      p.setFontSize(8);
      p.setTextColor(170, 170, 170);
      p.text("Generated by StudentNotes • shankar.com", 105, 292, { align: 'center' });
    };

    const imgData = canvas.toDataURL('image/jpeg', 0.85);

    // --- Multipage Logic ---
    let heightLeft = imgHeight;
    let position = 0;

    // Page 1
    pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
    addWatermark(pdf);
    heightLeft -= pdfHeight;

    // Subsequent Pages
    while (heightLeft > 0) {
      position = heightLeft - imgHeight; // Negative offset
      pdf.addPage();
      pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
      addWatermark(pdf);
      heightLeft -= pdfHeight;
    }

    pdf.save(`${fileName}.pdf`);

  } catch (err) {
    console.error("PDF Generation failed:", err);
    throw err; // Let the caller handle UI feedback (e.g., stopping loader)
  }
}